version: '3.6'

services:
  api:
    build: .
    entrypoint: sh -c "yarn && yarn start:dev"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/node/api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
      - "host.redis.internal:172.17.0.1"
      - "host.mssql.internal:172.17.0.1"